name: dpsnnn Cron Job

on:
  schedule:
    - cron: '0 1 * * *'
    - cron: '0 5 * * *'
    - cron: '0 9 * * *'
    - cron: '0 13 * * *'
    - cron: '0 17 * * *'
    - cron: '0 21 * * *'
  workflow_dispatch:

concurrency:
  group: run-bot
  cancel-in-progress: true

env:
  SENDER_GMAIL_USER: ${{ secrets.SENDER_GMAIL_USER }}
  SENDER_GMAIL_PASSWORD: ${{ secrets.SENDER_GMAIL_PASSWORD }}
  TARGET_GMAIL_USER: ${{ secrets.TARGET_GMAIL_USER }}
  G_SEARCH_LIST: ${{ secrets.G_SEARCH_LIST }}
  SS_SEARCH_LIST: ${{ secrets.SS_SEARCH_LIST }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
      - name: Bun install
        run: bun install --frozen-lockfile
      - name: Run script
        run: bun start
