name: Gamo2 Cron Job

on:
  schedule:
    - cron: '*/3 * * * *'
  workflow_dispatch:


env:
  SENDER_GMAIL_USER: ${{ secrets.SENDER_GMAIL_USER }}
  SENDER_GMAIL_PASSWORD: ${{ secrets.SENDER_GMAIL_PASSWORD }}
  TARGET_GMAIL_USER: ${{ secrets.TARGET_GMAIL_USER }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
      - name: Bun install
        run: bun install --frozen-lockfile
      - name: Run script
        run: bun start
